/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyRouteImport } from './routes/my'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PeoplePersonIdRouteImport } from './routes/people/$personId'
import { Route as MoviesNewRouteImport } from './routes/movies/new'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as DashboardUserIdRouteImport } from './routes/dashboard.$userId'
import { Route as UploadsPostersFileRouteImport } from './routes/uploads.posters.$file'
import { Route as UploadsChatFileRouteImport } from './routes/uploads.chat.$file'
import { Route as UploadsAvatarsFileRouteImport } from './routes/uploads.avatars.$file'
import { Route as MoviesMovieIdEditRouteImport } from './routes/movies/$movieId_.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesNewRoute = MoviesNewRouteImport.update({
  id: '/movies/new',
  path: '/movies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIdRoute = DashboardUserIdRouteImport.update({
  id: '/dashboard/$userId',
  path: '/dashboard/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsPostersFileRoute = UploadsPostersFileRouteImport.update({
  id: '/uploads/posters/$file',
  path: '/uploads/posters/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsChatFileRoute = UploadsChatFileRouteImport.update({
  id: '/uploads/chat/$file',
  path: '/uploads/chat/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsAvatarsFileRoute = UploadsAvatarsFileRouteImport.update({
  id: '/uploads/avatars/$file',
  path: '/uploads/avatars/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdEditRoute = MoviesMovieIdEditRouteImport.update({
  id: '/movies/$movieId_/edit',
  path: '/movies/$movieId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/friends': typeof FriendsRoute
  '/my': typeof MyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$userId': typeof DashboardUserIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/new': typeof MoviesNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/movies/$movieId/edit': typeof MoviesMovieIdEditRoute
  '/uploads/avatars/$file': typeof UploadsAvatarsFileRoute
  '/uploads/chat/$file': typeof UploadsChatFileRoute
  '/uploads/posters/$file': typeof UploadsPostersFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/friends': typeof FriendsRoute
  '/my': typeof MyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$userId': typeof DashboardUserIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/new': typeof MoviesNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/movies/$movieId/edit': typeof MoviesMovieIdEditRoute
  '/uploads/avatars/$file': typeof UploadsAvatarsFileRoute
  '/uploads/chat/$file': typeof UploadsChatFileRoute
  '/uploads/posters/$file': typeof UploadsPostersFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/friends': typeof FriendsRoute
  '/my': typeof MyRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$userId': typeof DashboardUserIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/new': typeof MoviesNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/movies/$movieId_/edit': typeof MoviesMovieIdEditRoute
  '/uploads/avatars/$file': typeof UploadsAvatarsFileRoute
  '/uploads/chat/$file': typeof UploadsChatFileRoute
  '/uploads/posters/$file': typeof UploadsPostersFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/friends'
    | '/my'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$userId'
    | '/movies/$movieId'
    | '/movies/new'
    | '/people/$personId'
    | '/dashboard/'
    | '/movies/'
    | '/movies/$movieId/edit'
    | '/uploads/avatars/$file'
    | '/uploads/chat/$file'
    | '/uploads/posters/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/friends'
    | '/my'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$userId'
    | '/movies/$movieId'
    | '/movies/new'
    | '/people/$personId'
    | '/dashboard'
    | '/movies'
    | '/movies/$movieId/edit'
    | '/uploads/avatars/$file'
    | '/uploads/chat/$file'
    | '/uploads/posters/$file'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/friends'
    | '/my'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$userId'
    | '/movies/$movieId'
    | '/movies/new'
    | '/people/$personId'
    | '/dashboard/'
    | '/movies/'
    | '/movies/$movieId_/edit'
    | '/uploads/avatars/$file'
    | '/uploads/chat/$file'
    | '/uploads/posters/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FriendsRoute: typeof FriendsRoute
  MyRoute: typeof MyRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DashboardUserIdRoute: typeof DashboardUserIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesNewRoute: typeof MoviesNewRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  MoviesMovieIdEditRoute: typeof MoviesMovieIdEditRoute
  UploadsAvatarsFileRoute: typeof UploadsAvatarsFileRoute
  UploadsChatFileRoute: typeof UploadsChatFileRoute
  UploadsPostersFileRoute: typeof UploadsPostersFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/new': {
      id: '/movies/new'
      path: '/movies/new'
      fullPath: '/movies/new'
      preLoaderRoute: typeof MoviesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$userId': {
      id: '/dashboard/$userId'
      path: '/dashboard/$userId'
      fullPath: '/dashboard/$userId'
      preLoaderRoute: typeof DashboardUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/posters/$file': {
      id: '/uploads/posters/$file'
      path: '/uploads/posters/$file'
      fullPath: '/uploads/posters/$file'
      preLoaderRoute: typeof UploadsPostersFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/chat/$file': {
      id: '/uploads/chat/$file'
      path: '/uploads/chat/$file'
      fullPath: '/uploads/chat/$file'
      preLoaderRoute: typeof UploadsChatFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/avatars/$file': {
      id: '/uploads/avatars/$file'
      path: '/uploads/avatars/$file'
      fullPath: '/uploads/avatars/$file'
      preLoaderRoute: typeof UploadsAvatarsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId_/edit': {
      id: '/movies/$movieId_/edit'
      path: '/movies/$movieId/edit'
      fullPath: '/movies/$movieId/edit'
      preLoaderRoute: typeof MoviesMovieIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FriendsRoute: FriendsRoute,
  MyRoute: MyRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DashboardUserIdRoute: DashboardUserIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesNewRoute: MoviesNewRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  MoviesMovieIdEditRoute: MoviesMovieIdEditRoute,
  UploadsAvatarsFileRoute: UploadsAvatarsFileRoute,
  UploadsChatFileRoute: UploadsChatFileRoute,
  UploadsPostersFileRoute: UploadsPostersFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
